In [68]:
#Importamos las librerias pandas y numpy
import pandas as pd
import numpy as np

In [69]:
#Leer archivo de Ventas por Asesor
ventas = pd.read_excel("Ventas_por_Asesor.xlsx")

ventas.head()

,Ventas X Mes,12,7,8,13,6,21,17,17.1,23,...,37,10,Unnamed: 31,Unnamed: 32,178,Unnamed: 34,397,Unnamed: 36,236,Unnamed: 38
0,NaN,2024-02-01 00:00:00,2024-03-01 00:00:00,2024-04-01 00:00:00,2024-05-01 00:00:00,2024-06-01 00:00:00,2024-07-01 00:00:00,2024-08-01 00:00:00,2024-09-01 00:00:00,2024-10-01 00:00:00,...,2026-06-01 00:00:00,2026-07-01 00:00:00,NaN,NaN,2024,NaN,2025,NaN,2026,NaN
1,Nombre vendedor,2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,811.0,Raking,Acum,Ranking,Acum,Ranking,Acum,Ranking
2,PEDRO GONZALEZ ESPINDOLA,,,1,2,,7,2,3,3,...,4,NaN,88.0,NaN,22,NaN,45,2,21,NaN
3,VICTOR MANUEL SANCHEZ ARRO,,,,,1,1,3,,2,...,3,2,88.0,NaN,11,NaN,51,NaN,26,NaN
4,MIGUEL ANGEL SONDEREGGER,,,,1,2,7,5,2,2,...,NaN,NaN,28.0,6,27,1,1,25,0,17

In [70]:
#Información general
ventas.info()

<class 'pandas.DataFrame'>
RangeIndex: 54 entries, 0 to 53
Data columns (total 39 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Ventas X Mes   53 non-null     str
 1   12             33 non-null     object
 2   7              32 non-null     object
 3   8              32 non-null     object
 4   13             32 non-null     object
 5   6              32 non-null     object
 6   21             32 non-null     object
 7   17             32 non-null     object
 8   17.1           32 non-null     object
 9   23             32 non-null     object
 10  22             32 non-null     object
 11  32             32 non-null     object
 12  26             33 non-null     object
 13  20             32 non-null     object
 14  30             31 non-null     object
 15  30.1           34 non-null     object
 16  34             32 non-null     object
 17  40             15 non-null     object
 18  36             14 non-null     object
 19  27             13 non-null     object
 20  38             16 non-null     object
 21  40.1           16 non-null     object
 22  42             14 non-null     object
 23  34.1           15 non-null     object
 24  38.1           14 non-null     object
 25  34.2           16 non-null     object
 26  41             16 non-null     object
 27  41.1           16 non-null     object
 28  35             13 non-null     object
 29  37             15 non-null     object
 30  10             9 non-null      object
 31  Unnamed: 31    52 non-null     float64
 32  Unnamed: 32    50 non-null     object
 33  178            53 non-null     object
 34  Unnamed: 34    50 non-null     object
 35  397            53 non-null     object
 36  Unnamed: 36    51 non-null     object
 37  236            53 non-null     object
 38  Unnamed: 38    50 non-null     object
dtypes: float64(1), object(37), str(1)
memory usage: 16.6+ KB

In [71]:
#Identificar valores nulos por columna
ventas.isnull().sum()

Ventas X Mes      1
12               21
7                22
8                22
13               22
6                22
21               22
17               22
17.1             22
23               22
22               22
32               22
26               21
20               22
30               23
30.1             20
34               22
40               39
36               40
27               41
38               38
40.1             38
42               40
34.1             39
38.1             40
34.2             38
41               38
41.1             38
35               41
37               39
10               45
Unnamed: 31       2
Unnamed: 32       4
178               1
Unnamed: 34       4
397               1
Unnamed: 36       3
236               1
Unnamed: 38       4
dtype: int64

In [72]:
#Convertir espacios vacíos en valores nulos
ventas = ventas.replace(r'^\s*$', np.nan, regex=True)

In [73]:
ventas.isnull().sum()

Ventas X Mes      1
12               46
7                48
8                48
13               46
6                48
21               46
17               47
17.1             45
23               42
22               40
32               40
26               38
20               41
30               45
30.1             41
34               43
40               39
36               40
27               41
38               38
40.1             38
42               40
34.1             39
38.1             40
34.2             38
41               38
41.1             38
35               41
37               39
10               45
Unnamed: 31       2
Unnamed: 32       4
178               1
Unnamed: 34       4
397               1
Unnamed: 36       3
236               1
Unnamed: 38       4
dtype: int64

In [74]:
#Crear copia del DataFrame
ventas2 = ventas.copy()

In [86]:
#Corregir los años de la fila correspondiente
#B3:L3 = 2024
ventas2.iloc[1, 1:12] = 2024

#M3:X3 = 2025
ventas2.iloc[1, 12:24] = 2025

#Y3:AE3 = 2026
ventas2.iloc[1, 24:31] = 2026

#Completar los años de la sección de acumulados/rankings

#AH2:AI2 = 2024
ventas2.iloc[0, 33:35] = 2024

#AJ2:AK2 = 2025
ventas2.iloc[0, 35:37] = 2025

#AL2:AM2 = 2026
ventas2.iloc[0, 37:39] = 2026

#Reemplazar todos los valores nulos de los meses por 0
ventas2.iloc[:, 1:31] = ventas2.iloc[:, 1:31].fillna(0)

print(ventas2.head())

                Ventas X Mes                    12                    7  \
0                         NaN  2024-02-01 00:00:00  2024-03-01 00:00:00
1             Nombre vendedor                 2024                 2024
2    PEDRO GONZALEZ ESPINDOLA                    0                    0
3  VICTOR MANUEL SANCHEZ ARRO                    0                    0
4    MIGUEL ANGEL SONDEREGGER                    0                    0

                     8                   13                    6  \
0  2024-04-01 00:00:00  2024-05-01 00:00:00  2024-06-01 00:00:00
1                 2024                 2024                 2024
2                    1                    2                    0
3                    0                    0                    1
4                    0                    1                    2

                    21                   17                 17.1  \
0  2024-07-01 00:00:00  2024-08-01 00:00:00  2024-09-01 00:00:00
1                 2024                 2024                 2024
2                    7                    2                    3
3                    1                    3                    0
4                    7                    5                    2

                    23  ...                   37                   10  \
0  2024-10-01 00:00:00  ...  2026-06-01 00:00:00  2026-07-01 00:00:00
1                 2024  ...                 2026                 2026
2                    3  ...                    4                    0
3                    2  ...                    3                    2
4                    2  ...                    0                    0

  Unnamed: 31 Unnamed: 32   178 Unnamed: 34   397 Unnamed: 36    236  \
0         NaN         NaN  2024        2024  2025        2025   2026
1       811.0      Raking  Acum     Ranking  Acum     Ranking  Acum
2        88.0         NaN    22         NaN    45           2     21
3        88.0         NaN    11         NaN    51         NaN     26
4        28.0           6    27           1     1          25      0

  Unnamed: 38
0        2026
1     Ranking
2         NaN
3         NaN
4          17

[5 rows x 39 columns]

In [87]:
#Comprobar valores nulos
ventas2.isnull().sum()

Ventas X Mes     1
12               0
7                0
8                0
13               0
6                0
21               0
17               0
17.1             0
23               0
22               0
32               0
26               0
20               0
30               0
30.1             0
34               0
40               0
36               0
27               0
38               0
40.1             0
42               0
34.1             0
38.1             0
34.2             0
41               0
41.1             0
35               0
37               0
10               0
Unnamed: 31      2
Unnamed: 32      4
178              1
Unnamed: 34      3
397              1
Unnamed: 36      2
236              1
Unnamed: 38      3
dtype: int64

In [88]:
#Total de valores nulos
ventas2.isnull().sum().sum()

np.int64(18)

In [89]:
#Crear archivo CSV final
ventas2.to_csv(
    "Ventas_por_Asesor_Sin_Nulos.csv",
    index=False
)

In [79]:
#Leer archivo Principales Canales
canales = pd.read_excel("Principales_Canales.xlsx")
canales.head()

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32,Unnamed: 33,Unnamed: 34
0,NaN,NaN,NaN,Datos erroneos no confiables de Sale-U,NaN,NaN,NaN,-,Sin datos,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Ventas X Mes,Ventas Reportadas,12,7,8,13,6,21,17,17,...,38,30,41,41,35,37,NaN,NaN,NaN,NaN
3,Piso,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Conversion,NaN,NaN
4,Piso,"Febrero, 24","Marzo, 24","Abril, 24","Mayo, 24","Junio, 24","Julio, 24","Agosto, 24","Septiembre, 24","Octubre, 24",...,"Febrero, 26","Marzo, 26","Abril, 26","Mayo, 26","Junio, 26","Julio,26",NaN,Historica,Año actual,Ultimos 3 meses

In [80]:
#Identificar valores nulos por columna
canales.isnull().sum()

Unnamed: 0     12
Unnamed: 1     25
Unnamed: 2     20
Unnamed: 3     18
Unnamed: 4     19
Unnamed: 5     17
Unnamed: 6     17
Unnamed: 7     17
Unnamed: 8     16
Unnamed: 9     17
Unnamed: 10    17
Unnamed: 11    16
Unnamed: 12    15
Unnamed: 13    12
Unnamed: 14    12
Unnamed: 15    12
Unnamed: 16    12
Unnamed: 17    15
Unnamed: 18    15
Unnamed: 19    13
Unnamed: 20    13
Unnamed: 21    13
Unnamed: 22    13
Unnamed: 23    12
Unnamed: 24    11
Unnamed: 25    21
Unnamed: 26    21
Unnamed: 27    21
Unnamed: 28    21
Unnamed: 29    21
Unnamed: 30    24
Unnamed: 31    58
Unnamed: 32    28
Unnamed: 33    40
Unnamed: 34    40
dtype: int64

In [81]:
#Crear copia del DataFrame
canales2 = canales.copy()

In [82]:
#Completar bloques provenientes de celdas combinadas

#A5:AE5 = Piso
canales2.iloc[3, 0:31] = "Piso"

#A18:AE18 = Plazas
canales2.iloc[16, 0:31] = "Plazas"

#A33:AE33 = Digital
canales2.iloc[31, 0:31] = "Digital"

#A46:AE46 = Digital
canales2.iloc[44, 0:31] = "Digital"

#Completar títulos de indicadores en AG:AI
canales2.iloc[3, 32:35] = "Conversion"
canales2.iloc[7, 32:35] = "Aporte"
canales2.iloc[11, 32:35] = "Cota (Ventas) Ultimos 6ms"

canales2.iloc[16, 32:35] = "Conversion"
canales2.iloc[20, 32:35] = "Aporte"
canales2.iloc[26, 32:35] = "Cota (Ventas) Ultimos 6ms"

canales2.iloc[31, 32:35] = "Conversion"
canales2.iloc[35, 32:35] = "Aporte"
canales2.iloc[39, 32:35] = "Cota (Ventas) Ultimo Semestre"

#Reemplazar valores nulos por 0 en las columnas numéricas de meses
#Bloque Piso
canales2.iloc[5:14, 1:31] = (
    canales2.iloc[5:14, 1:31]
    .replace("-", 0)
    .fillna(0)
)

#Bloque Plazas
canales2.iloc[18:29, 1:31] = (
    canales2.iloc[18:29, 1:31]
    .replace("-", 0)
    .fillna(0)
)

#Primer bloque Digital
canales2.iloc[33:42, 1:31] = (
    canales2.iloc[33:42, 1:31]
    .replace("-", 0)
    .fillna(0)
)

#Segundo bloque Digital
canales2.iloc[46:55, 1:31] = (
    canales2.iloc[46:55, 1:31]
    .replace("-", 0)
    .fillna(0)
)

In [83]:
#Comprobar valores nulos por columna
canales2.isnull().sum()

Unnamed: 0     12
Unnamed: 1     10
Unnamed: 2      9
Unnamed: 3      7
Unnamed: 4      9
Unnamed: 5      8
Unnamed: 6      8
Unnamed: 7      7
Unnamed: 8      7
Unnamed: 9      8
Unnamed: 10     8
Unnamed: 11     7
Unnamed: 12     7
Unnamed: 13     4
Unnamed: 14     4
Unnamed: 15     4
Unnamed: 16     4
Unnamed: 17     7
Unnamed: 18     7
Unnamed: 19     7
Unnamed: 20     7
Unnamed: 21     7
Unnamed: 22     7
Unnamed: 23     7
Unnamed: 24     7
Unnamed: 25     8
Unnamed: 26     8
Unnamed: 27     8
Unnamed: 28     8
Unnamed: 29     8
Unnamed: 30    10
Unnamed: 31    58
Unnamed: 32    28
Unnamed: 33    31
Unnamed: 34    31
dtype: int64

In [84]:
#Comprobar total de valores nulos
canales2.isnull().sum().sum()

np.int64(377)

In [85]:
#Crear archivo CSV final
canales2.to_csv(
    "Principales_Canales_Sin_Nulos.csv",
    index=False
)

In [90]:
#En las columnas de la base de datos ventas por asesor, a los meses de 2024, 2025 y 2026, los valores nulos los reemplazé por 0 
# mediante el método fillna(0), debido a que si no había información en estas variables se entendió como que no hbuo 
# ventas registradas para ese periodo. Además, se corrigieron manualmente los valores correspondientes 
# a los años 2024, 2025 y 2026 en las filas utilizadas como encabezados de los diferentes periodos y en las secciones 
# de acumulados y rankings. Finalmente, se verificó nuevamente la cantidad de valores nulos con isnull().sum() y isnull().sum().sum(). 
# Una vez realizado esto, el DataFrame limpio se exportó como Ventas_por_Asesor_Sin_Nulos.csv

#En las columnas de la base de datos de principales canales, se completaron manualmente los valores de las categorías Piso, Plazas 
# y Digital, manteniendo la estructura y clasificación original de los datos. De igual manera, se completaron los títulos 
# correspondientes a los indicadores Conversión, Aporte y Cota de Ventas de los últimos seis meses o semestre, según cada sección. 
# Para las columnas numéricas correspondientes a los meses, se utilizaron dos técnicas de limpieza. Primero, los valores 
# representados mediante un guion ("-") fueron sustituidos por 0 utilizando replace("-", 0). Posteriormente, los valores 
# nulos restantes fueron reemplazados mediante fillna(0). Este procedimiento se aplicó por separado en los bloques correspondientes 
# a Piso, Plazas y Digital, considerando que un dato vacío dentro de estas variables numéricas representa la ausencia de un valor 
# registrado. Finalmente, se comprobó nuevamente la cantidad de valores nulos por columna y en todo el dataset. Después del 
# tratamiento, el archivo limpio se exportó con el nombre Principales_Canales_Sin_Nulos.csv.